### PR TITLE
Make default mimetypes specific to pantheon

### PR DESCRIPTION
**Pull request by worldofpeace**
By naming this file pantheon-mimeapps.list they will only be applied if the current desktop
is Pantheon.

See the [Mime Apps Spec](https://specifications.freedesktop.org/mime-apps-spec/latest/ar01s02.html) for reference.

### CODE REVIEW

**Comment by worldofpeace** [comment]
Seems that [Pop OS](https://github.com/pop-os/default-settings/blob/master_cosmic/usr/share/applications/pop-mimeapps.list) is already doing this.

**Comment by worldofpeace** [comment]
ping @danrabbit @codygarver

**Comment by cassidyjames** [comment]
@worldofpeace please do not just ping people on issues, it just adds to noise here. @codygarver has been requested as a reviewer and will take a look when he is able.

**Comment by worldofpeace** [comment]
> @worldofpeace please do not just ping people on issues, it just adds to noise here. @codygarver has been requested as a reviewer and will take a look when he is able.

I understand, I was just trying to prevent my change from being forgotten. 
Especially when it is trivial and done in most distros.

**Comment by worldofpeace** [comment]
I'm going to update this for the meson packaging now.

**Comment by worldofpeace** [comment]
https://github.com/elementary/session-settings/pull/12/commits/fb7d4ba50148b7c623363a7efaf302f8f7470404 makes the meson option semantically correct.

**Comment by worldofpeace** [comment]
I've wrote this patch 7 months ago, no merge?
I don't think this is a PR I want to pursue anymore. 
Ff anyone feels like integrating this, the patch will continue to exist in its closed state.

**Comment by cassidyjames** [comment]
Leaving open since it's still outstanding, and we were waiting on @codygarver to review. I've reached out to him and others in Slack to see if we can get this merged.

**Comment by worldofpeace** [comment]
FTR, already had this as a downstream patch in NixOS for the duration of its opening.

**Pull request merged**
